/**
 * Home component
 *
 * The section at the top of the page to display image of your
 * choice, name and title that describes your career focus.
 */

import React from "react";
import arrowSvg from "../images/down-arrow.svg";
import PropTypes from "prop-types";

/**
 * Home background image
 */
import backgroundImage from "../images/BackGround_Home_JEVG.png";
import eegComparisonImage from "../images/EEGComparison_JEVG.svg";

const imageAltText = "Background image of synthetic EEG signal visualization";

const Home = ({ name, title, nameFontSize, titleFontSize }) => {
  return (
    <section id="home" className="min-height" style={{ position: "relative" }}>
      <img className="background" src={backgroundImage} alt={imageAltText} style={{ width: "150%", height: "150%", objectFit: "cover", position: "absolute", zIndex: -2 }} />
      <div style={{ backgroundColor: "rgba(0, 0, 0, 0.75)", position: "absolute", top: 0, left: 0, right: 0, bottom: 0, zIndex: -1 }}></div>
      <div style={{ position: "absolute", top: "5rem", left: "2rem", width: "40%", color: "white" }}>
        <h1 style={{ fontSize: nameFontSize }}>{name}</h1>
        <h2 style={{ fontSize: titleFontSize, fontWeight: "300" }}>{title}</h2>
      </div>
      <div style={{ position: "absolute", top: "5rem", right: "4rem", width: "40%", color: "white", textAlign: "right" }}>
        <img src={eegComparisonImage} alt="EEG signal comparison" style={{ width: "100%", marginBottom: "1rem" }} />
        <p style={{ fontSize: "1rem", lineHeight: "1.5" }}>
          Pronounced slow (about 1.5/sec) spike wave complexes in generalized synchrony, Extracts of [2] (Left), and synthetic EEG signal generated by the algorithm by modifying its parameters to emulate the real signal. (Right))
        </p>
        <p style={{ fontSize: "0.85rem", fontStyle: "italic" }}>
          [2] E. Niedermeyer and F.L. da Silva, Electroencephalography: Basic Principles, Clinical Applications, and Related Fields, 5th ed. Baltimore, MD, USA: Lippincott Williams & Wilkins, 2005.
        </p>
      </div>
      <div style={{ position: "absolute", bottom: "3rem", left: "50%", transform: "translateX(-50%)" }}>
        <img src={arrowSvg} style={{ height: "3rem", width: "3rem" }} alt="Scroll down arrow" />
      </div>
    </section>
  );
};

Home.defaultProps = {
  name: "Synthetic EEG Signal Generator of Morphologies",
  title: "Landing page for project versions",
  nameFontSize: "5rem",
  titleFontSize: "1.5rem",
};

Home.propTypes = {
  name: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  nameFontSize: PropTypes.string,
  titleFontSize: PropTypes.string,
};

export default Home;
